from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from market_signal_lab.reviewer_acceptance_scorecard import (
    REVIEWER_ACCEPTANCE_METADATA_KEYS,
    REVIEWER_ACCEPTANCE_NEXT_ACTION_KEYS,
    REVIEWER_ACCEPTANCE_SCORECARD_ITEM_KEYS,
    REVIEWER_ACCEPTANCE_SCORECARD_TOP_LEVEL_KEYS,
    build_reviewer_acceptance_scorecard,
    render_reviewer_acceptance_scorecard,
)


def test_reviewer_acceptance_scorecard_builds_expected_static_payload() -> None:
    payload = build_reviewer_acceptance_scorecard()
    markdown = render_reviewer_acceptance_scorecard(payload)

    assert tuple(payload) == REVIEWER_ACCEPTANCE_SCORECARD_TOP_LEVEL_KEYS
    assert payload["artifact_type"] == "reviewer_acceptance_scorecard"
    assert payload["schema_version"] == "1.0"
    assert payload["research_only"] is True
    assert payload["static_only"] is True
    assert payload["historical_diagnostics_only"] is True
    assert payload["no_live_data"] is True
    assert payload["no_broker_or_account"] is True
    assert payload["no_orders_or_position_sizing"] is True
    assert payload["no_recommendations_or_forecasts"] is True
    assert payload["not_investment_advice"] is True
    assert payload["overall_label"] == "WARN"
    assert payload["default_outputs"] == {
        "markdown": "reports/reviewer-acceptance-scorecard.md",
        "json": "reports/reviewer-acceptance-scorecard.json",
    }
    assert tuple(payload["acceptance_metadata"]) == REVIEWER_ACCEPTANCE_METADATA_KEYS
    assert payload["acceptance_metadata"] == {
        "version": "1.0",
        "generated_by": (
            "python -m market_signal_lab.cli --reviewer-acceptance-scorecard"
        ),
        "review_scope": "static public reviewer acceptance scorecard artifacts",
    }
    assert [item["category"] for item in payload["scorecard"]] == [
        "public_review_readiness",
        "reproducibility_evidence",
        "risk_boundaries",
        "next_actions",
    ]
    assert all(
        tuple(item) == REVIEWER_ACCEPTANCE_SCORECARD_ITEM_KEYS
        for item in payload["scorecard"]
    )
    assert all(
        tuple(item) == REVIEWER_ACCEPTANCE_NEXT_ACTION_KEYS
        for item in payload["next_actions"]
    )
    assert "reports/index.html" in payload["artifact_paths"][
        "public_review_readiness"
    ]
    assert "reports/cross-asset-thesis-ledger-acceptance.md" in payload[
        "artifact_paths"
    ]["reproducibility_evidence"]
    stress_kit_paths = {
        "reports/strategy-assumption-stress-kit.md",
        "reports/strategy-assumption-stress-kit.json",
        "reports/strategy-assumption-stress-kit.html",
    }
    scorecard_evidence_paths = {
        path for item in payload["scorecard"] for path in item["evidence_paths"]
    }
    assert stress_kit_paths <= scorecard_evidence_paths
    assert stress_kit_paths <= set(payload["artifact_paths"]["risk_boundaries"])
    assert payload["does_not_prove"] == [
        (
            "Profitability, future robustness, investment suitability, or "
            "financial correctness."
        ),
        (
            "Trading readiness, broker execution readiness, order-routing "
            "safety, or position-sizing appropriateness."
        ),
        (
            "Completeness for every reviewer audience, regulatory use, "
            "compliance approval, or production deployment."
        ),
    ]
    assert "# Reviewer Acceptance Scorecard" in markdown
    assert "## Metadata" in markdown
    assert "- **Version**: 1.0" in markdown
    assert (
        "- **Generated by**: "
        "`python -m market_signal_lab.cli --reviewer-acceptance-scorecard`"
    ) in markdown
    assert (
        "- **Review scope**: static public reviewer acceptance scorecard artifacts"
    ) in markdown
    assert "| public_review_readiness | PASS |" in markdown
    assert "reports/reviewer-acceptance-scorecard.md" in markdown
    assert "no live data" in markdown
    assert "investment advice" in markdown
    assert "## What this does not prove" in markdown
    assert (
        "Profitability, future robustness, investment suitability, or "
        "financial correctness."
    ) in markdown


def test_reviewer_acceptance_scorecard_builds_fresh_nested_objects() -> None:
    payload = build_reviewer_acceptance_scorecard()
    payload["scorecard"][0]["evidence_paths"].append("unexpected.md")
    payload["next_actions"][0]["unexpected"] = "extra"
    payload["does_not_prove"].append("unexpected")

    fresh_payload = build_reviewer_acceptance_scorecard()

    assert "unexpected.md" not in fresh_payload["scorecard"][0]["evidence_paths"]
    assert "unexpected" not in fresh_payload["does_not_prove"]
    assert tuple(fresh_payload["next_actions"][0]) == (
        REVIEWER_ACCEPTANCE_NEXT_ACTION_KEYS
    )


def test_reviewer_acceptance_scorecard_evidence_paths_are_available() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    env = os.environ.copy()
    env["PYTHONPATH"] = str(repo_root)
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "market_signal_lab.cli",
            "--reviewer-acceptance-scorecard",
        ],
        cwd=repo_root,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""

    payload = build_reviewer_acceptance_scorecard()
    generated_outputs = set(payload["default_outputs"].values())
    evidence_paths = {
        path
        for item in payload["scorecard"]
        for path in item["evidence_paths"]
    }
    artifact_paths = {
        path for paths in payload["artifact_paths"].values() for path in paths
    }

    assert artifact_paths <= evidence_paths
    assert all((repo_root / path).is_file() for path in evidence_paths)

    git_result = subprocess.run(
        [
            "git",
            "ls-files",
            "--cached",
            "--others",
            "--exclude-standard",
            *sorted(evidence_paths - generated_outputs),
        ],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    )
    assert git_result.returncode == 0
    assert set(git_result.stdout.splitlines()) == evidence_paths - generated_outputs


def test_cli_writes_reviewer_acceptance_scorecard_defaults(tmp_path: Path) -> None:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(Path(__file__).resolve().parents[1])
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "market_signal_lab.cli",
            "--reviewer-acceptance-scorecard",
        ],
        cwd=tmp_path,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""
    markdown_path = tmp_path / "reports" / "reviewer-acceptance-scorecard.md"
    json_path = tmp_path / "reports" / "reviewer-acceptance-scorecard.json"
    markdown = markdown_path.read_text(encoding="utf-8")
    payload = json.loads(json_path.read_text(encoding="utf-8"))
    assert "# Reviewer Acceptance Scorecard" in markdown
    assert "## What this does not prove" in markdown
    assert "Profitability, future robustness" in markdown
    assert payload["artifact_type"] == "reviewer_acceptance_scorecard"
    assert payload["acceptance_metadata"]["generated_by"] == (
        "python -m market_signal_lab.cli --reviewer-acceptance-scorecard"
    )
    assert "does_not_prove" in payload
    assert payload["overall_label"] == "WARN"
    assert payload["no_live_data"] is True
    assert payload["not_investment_advice"] is True


def test_cli_reviewer_acceptance_scorecard_custom_outputs(
    tmp_path: Path,
) -> None:
    markdown_path = tmp_path / "scorecard.md"
    json_path = tmp_path / "scorecard.json"

    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "market_signal_lab.cli",
            "--reviewer-acceptance-scorecard",
            "--output",
            str(markdown_path),
            "--json-output",
            str(json_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert result.stdout == ""
    assert "# Reviewer Acceptance Scorecard" in markdown_path.read_text(
        encoding="utf-8"
    )
    assert json.loads(json_path.read_text(encoding="utf-8"))[
        "acceptance_metadata"
    ]["review_scope"] == "static public reviewer acceptance scorecard artifacts"


@pytest.mark.parametrize(
    ("extra_args", "message"),
    [
        (
            ["examples/data/sample_tqqq_qld_like.csv"],
            "--reviewer-acceptance-scorecard does not take csv_path",
        ),
        (
            ["--config", "examples/configs/single-backtest-report.json"],
            "--reviewer-acceptance-scorecard does not take --config",
        ),
        (
            ["--html-output", "scorecard.html"],
            "--reviewer-acceptance-scorecard writes Markdown/JSON, not HTML",
        ),
        (
            ["--manifest-output", "manifest.md"],
            "--reviewer-acceptance-scorecard does not write experiment manifests",
        ),
        (
            ["--reviewer-evidence-bundle"],
            (
                "--reviewer-acceptance-scorecard cannot be combined with "
                "--reviewer-evidence-bundle"
            ),
        ),
        (
            ["--pretrade-packet"],
            (
                "--reviewer-acceptance-scorecard cannot be combined with "
                "--pretrade-packet"
            ),
        ),
        (
            ["--prediction-readiness-audit"],
            (
                "--prediction-readiness-audit cannot be combined with "
                "--reviewer-acceptance-scorecard"
            ),
        ),
        (
            ["--sweep"],
            "--reviewer-acceptance-scorecard cannot be combined with --sweep",
        ),
    ],
)
def test_cli_reviewer_acceptance_scorecard_rejects_incompatible_options(
    extra_args: list[str],
    message: str,
) -> None:
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "market_signal_lab.cli",
            "--reviewer-acceptance-scorecard",
            *extra_args,
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 2
    assert message in result.stderr
